apiVersion: v1
kind: Service
metadata:
  name: simple-ss
  labels:
    app: simple-ss
spec:
  clusterIP: None
  selector:
    app: simple-ss
  ports:
    - name: http
      port: 9085
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: simple-ss
  labels:
    app: simple-ss
spec:
  serviceName: simple-ss
  replicas: 2
  selector:
    matchLabels:
      app: simple-ss
  template:
    metadata:
      labels:
        app: simple-ss
    spec:
      containers:
      - name: helloworld
        image: ghcr.io/pipe-cd/helloworld:v0.33.0
        args:
          - server
        ports:
        - containerPort: 9085
        envFrom:
        - configMapRef:
            name: ss-config
