apiVersion: apps/v1
kind: Deployment
metadata:
  name: with-init
  labels:
    app: with-init
spec:
  replicas: 2
  selector:
    matchLabels:
      app: with-init
  template:
    metadata:
      labels:
        app: with-init
    spec:
      initContainers:
        - name: init-setup
          image: busybox:1.36
          command: ["sh", "-c", "echo init complete"]
      containers:
        - name: helloworld
          image: ghcr.io/pipe-cd/helloworld:v0.33.0
          args:
            - server
          ports:
            - containerPort: 9085
